name: Tests
on:
  pull_request:

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build
        run: |
          npm i -g npm@8
          npm ci
          npm run build
          npm link

      - name: Test
        run: npm test
